version: "3.9"

services: 

  redis:
    image: "redis:latest"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./redis/data:/data"
      - "./redis/conf:/usr/local/etc/redis"

  server:
    image: "linguine:latest"
    build:
      # default target
      context: .
    command: 
      - "node"
      - "src/index.js"
    ports:
      - "8080:8080"
    working_dir: "/app"
    environment: 
      - "NODE_ENV=development"
      - "DISCORD_TOKEN=${DISCORD_TOKEN}"
    volumes:
      - "./src:/app/src"
      - "/tmp/apps:/tmp/apps"
