version: "3.9"

services: 

  redis:
    image: "redis:latest"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./redis/data:/data"
      - "./redis/conf:/usr/local/etc/redis"

  server:
    image: "linguine:latest"
    build:
      # default target
      context: .
    command: 
      - "node"
      - "src/index.mjs"
    restart: always
    working_dir: "/app"
    environment: 
      - "NODE_ENV=${NODE_ENV:-production}"
      - "DISCORD_TOKEN=${DISCORD_TOKEN}"
      - "CLIENT_ID=${CLIENT_ID}"
      - "CLIENT_SECRET=${CLIENT_SECRET}"
      - "BOT_LINK=${BOT_LINK}"
      - "REDIRECT_URI=${REDIRECT_URI}"
